yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        '<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('auth/', include('users.urls', namespace="users")),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace="posts")),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return f'Group: {self.slug}'


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return f'{self.text[:15]}, {self.pub_date}, {self.group}'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=None
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"Последователь: '{self.user}', автор: '{self.author}'"

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        help_text = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение',
        }
        labels = {
            'group': 'Группа',
            'text': 'Текст',
            'image': 'Изображение',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_text = {
            'text': 'Комментарий',
        }
        labels = {
            'text': 'Комментарий',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post, User
from .utils import pagination_fun
from django.http import HttpResponseRedirect


@cache_page(20)
def index(request):
    post_list = Post.objects.select_related('group', 'author')

    page_obj = pagination_fun(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('group', 'author')

    page_obj = pagination_fun(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group', 'author')

    page_obj = pagination_fun(post_list, request)
    context = {
        'author': author,
        'page_obj': page_obj,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # comments = post.comments.filter(active=True)
    comments = post.comments.all()
    form = CommentForm()

    # if request.method == 'POST':
    #     comment_form = CommentForm(data=request.POST)
    #     if comment_form.is_valid():
    #         new_comment = comment_form.save(commit=False)
    #         new_comment.post = post
    #         new_comment.save()
    # else:
    #     comment_form = CommentForm()
    return render(request,
                  'posts/post_detail.html',
                  {
                      'post': post,
                      'comments': comments,
                      'form': form
                  })


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    authors = user.follower.values_list('author', flat=True)
    posts_list = Post.objects.filter(author__id__in=authors)

    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(
        request,
        'posts/follow.html',
        {'page': page, 'paginator': paginator}
    )


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
        return redirect(
            'profile',
            username=username
        )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.get(user=user, author__username=username).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit%}
    Редактировать пост
  {% else %}
    Создать новый пост
  {% endif %}
{% endblock title %}
{% block content %}
{% load user_filters %}
<div class="col-md-8 p-5">
  <div class="card">
    <div class="card-header">
      {% if is_edit%}
        Редактировать пост
      {% else %}
        Новый пост
      {% endif %}
    </div>
    <div class="card-body">
      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
      {% endif %}

      {% if is_edit %}
        <form method="post" action="{% url 'posts:post_edit' post.id %}" enctype="multipart/form-data">
      {% else %}
        <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
      {% endif %}
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group row my-3"
          {% if field.field.required %}
            aria-required="true"
          {% else %}
            aria-required="false"
          {% endif %}>
          <label for="{{ field.id_for_label }}">
          {{ field.label }}
            {% if field.field.required %}
              <span class="required text-danger">*</span>
            {% endif %}
          </label>
          <div>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
          </div>
        </div>
      {% endfor %}
      <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary">
          {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
        </button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %} Посты избранных {% endblock %}

{% block content %}
    <div class="container">

        {% include "posts/menu.html" with follow=True %}

        <h1> Последние обновления избранных авторов </h1>
        {% for post in page %}
            {% include "posts/card_post.html" with post=post %}
        {% endfor %}

    </div>

        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock title %}
{% load thumbnail %}
{% block content %}
  <h1> {{ group.title }} </h1>
  <p> {{ group.description|linebreaksbr }} </p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          <a href="{% url 'posts:profile' post.author.username %}">
            Автор: {{ post.author.get_full_name }}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li>
          <a href="{% url 'posts:post_detail' post.id %}">
          Страница поста: {{ post.author.post.id }}</a>
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% cache 20 index %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
          <a href="{% url 'posts:profile' post.author.username %}">Автор: {{ author.get_full_name }}</a>
      </li>
      <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы {{ post.group.title }}</a>
    {% endif %}

    {% if not forloop.last %}
    <hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content%}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock title %}
{% load thumbnail %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li class="list-group-item">
          Группа:
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group.slug }}</a>
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        <li class="list-group-item">
          {% if user == post.author %}
          <a href="{% url 'posts:post_edit' post.id %}">
            редактировать пост
          </a>
          {% endif %}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>

      {% load user_filters %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}


      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaks }}
      </p>
    </article>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ post.author }} {% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ post.author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if following %}
      <a class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button">
        Отписаться
      </a>
    {% else %}
        <a class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button">
          Подписаться
        </a>
    {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
           <a href="{% url 'posts:profile' post.author.username %}"> все посты пользователя {{ author.get_full_name }}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.slug }}</a>
    {% endif %}
    <hr>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content%}

yatube/templates/posts/update_post.html
{% block content %}
<ul class="nav  nav-pills">
  <li class="nav-item">
    <a class="nav-link" href="../about/author.html">
      Об авторе
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../about/tech.html">
      Технологии
    </a>
  </li>
  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link active" href="../posts/create_post.html">
        Новая запись
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light " href="../users/password_change_form.html">
        Изменить пароль
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
    </li>
    <li>
      Пользователь: leo
    <li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link link-light" href="../users/login.html">
      Войти
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
  </li>
  {% endif %}
</ul>

<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Редактировать пост
          </div>
          <div class="card-body">
            <form method="post" action="../posts/create_post.html">
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger" >*</span>
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                </textarea>
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                <select name="group" class="form-control" id="id_group">
                  <option value="">---------</option>
                  <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                </select>
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Добавить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content%}